const root = document.getElementById('root');
const state = { view: 'dashboard', health: null, path: '', result: null, error: '' };
function escapeHtml(value) { return String(value).replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch])); }
function json(value) { return escapeHtml(JSON.stringify(value, null, 2)); }
function navButton(view, label) { return `<button data-view="${view}" class="${state.view===view?'active':''}">${label}</button>`; }
function shell(content) { const version = state.health ? `v${escapeHtml(state.health.version)}` : 'v0.3.0'; return `<div class="shell"><header><strong>REPROSEC CAPSULE</strong><span>imr :: ${version}</span><div class="mode">PASSIVE</div></header><aside aria-label="Primary navigation">${navButton('dashboard','Dashboard')}${navButton('workspace','Workspace')}${navButton('integrity','Integrity')}</aside><main>${content}</main></div>`; }
function feedback() { const error = state.error ? `<p role="alert" class="error">${escapeHtml(state.error)}</p>` : ''; const result = state.result ? `<div class="result"><pre>${json(state.result)}</pre></div>` : ''; return error + result; }
function dashboard() { return `<section class="hero"><div><p class="eyebrow">Evidence-native security research</p><h1>Portable proof, not opaque conclusions.</h1><p>Capture and normalize evidence, redact secrets, replay through deterministic safety gates, and keep every conclusion traceable.</p></div><div class="status"><span>API</span><b>${escapeHtml(state.health?.status ?? 'offline')}</b><span>AI</span><b>OFF</b><span>Cloud uploads</span><b>OFF</b></div></section><section class="grid"><article><h2>Evidence lineage</h2><p>Request → observation → workflow → response evidence → deterministic assertion</p></article><article><h2>Safety gate</h2><p>Scope → Policy → Rate Limit → Approval → Executor</p></article><article><h2>Runtime</h2><p class="big">${state.health ? `v${escapeHtml(state.health.version)}` : 'Unavailable'}</p><small>Local API status</small></article></section><section class="panel"><h2>Start locally</h2><div class="empty"><code>reprosec demo --output demo-capsule</code><br>Inspect, redact, pack, verify and report without any API key.</div></section>`; }
function workspace() { return `<section class="panel integrity"><p class="eyebrow">Local evidence workspace</p><h1>Inspect without mutating evidence</h1><label for="workspace-path">Capsule directory or .rcap path</label><input id="workspace-path" value="${escapeHtml(state.path)}" placeholder="/path/to/capsule"><div class="actions"><button data-api="/api/v1/workspace/inspect">Inspect</button><button data-api="/api/v1/workspace/redaction-preview">Redaction preview</button><button data-api="/api/v1/workspace/timeline">Timeline</button></div>${feedback()}</section>`; }
function integrity() { const verdict = state.result && Object.prototype.hasOwnProperty.call(state.result, 'valid') ? `<strong>${state.result.valid ? 'VALID' : 'INVALID'}</strong>` : ''; return `<section class="panel integrity"><p class="eyebrow">Deterministic verification</p><h1>Verify a local .rcap</h1><label for="capsule-path">Absolute capsule path</label><div class="formrow"><input id="capsule-path" value="${escapeHtml(state.path)}" placeholder="/path/to/finding.rcap"><button data-api="/api/v1/verify">Verify</button></div>${state.error ? `<p role="alert" class="error">${escapeHtml(state.error)}</p>` : ''}${state.result ? `<div class="result">${verdict}<pre>${json(state.result)}</pre></div>` : ''}</section>`; }
function render() { root.innerHTML = shell(state.view === 'workspace' ? workspace() : state.view === 'integrity' ? integrity() : dashboard()); root.querySelectorAll('[data-view]').forEach(el => el.addEventListener('click', () => { state.view = el.dataset.view; state.error=''; state.result=null; render(); })); root.querySelectorAll('input').forEach(el => el.addEventListener('input', () => { state.path = el.value; })); root.querySelectorAll('[data-api]').forEach(el => el.addEventListener('click', () => request(el.dataset.api))); }
async function request(endpoint) { state.error=''; state.result=null; if (!state.path.trim()) { state.error='A local capsule path is required.'; render(); return; } try { const response = await fetch(`${endpoint}?path=${encodeURIComponent(state.path)}`); const body = await response.json(); if (!response.ok) throw new Error(body.detail || 'Request failed'); state.result = body; } catch (error) { state.error = error instanceof Error ? error.message : 'Request failed'; } render(); }
render(); fetch('/api/v1/health').then(r => r.json()).then(body => { state.health = body; render(); }).catch(() => { state.health = null; render(); });