const root=document.getElementById('root');
const state={view:'dashboard',health:null,path:'',result:null,error:''};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const json=v=>esc(JSON.stringify(v,null,2));
function nav(view,label){return `<button data-view="${view}" class="${state.view===view?'active':''}">${label}</button>`}
function shell(body){const v=state.health?`v${esc(state.health.version)}`:'v0.4.0';return `<div class="shell"><header><div><strong>REPROSEC CAPSULE</strong><span>imr :: ${v}</span></div><div class="badges"><span>AI OFF</span><span>UPLOADS OFF</span><span>RCAP 0.3</span></div></header><aside>${nav('dashboard','Dashboard')}${nav('workspace','Workspace')}${nav('integrity','Integrity')}${nav('capabilities','Capabilities')}</aside><main>${body}</main></div>`}
function feedback(){return `${state.error?`<p class="error" role="alert">${esc(state.error)}</p>`:''}${state.result?`<div class="result"><pre>${json(state.result)}</pre></div>`:''}`}
function dashboard(){return `<section class="hero"><p class="eyebrow">Evidence-Native Security Research Intelligence</p><h1>Portable proof. Deterministic validation. Human control.</h1><p>Capture authorized evidence, model multi-actor workflows, redact secrets, replay through Scope/Policy/Rate/Approval gates, and preserve provenance in RCAP.</p></section><section class="grid"><article><b>RCAP 0.3</b><p>Actors, sessions, evidence, network observations, validation records and signatures.</p></article><article><b>Safety Gate</b><p>Scope → Policy → Rate Limit → Approval → Executor.</p></article><article><b>Capture</b><p>Authorized HTTP capture and browser-event recording. Capture never equals validation.</p></article><article><b>Runtime</b><p>${state.health?`API ${esc(state.health.status)} · v${esc(state.health.version)}`:'API unavailable'}</p></article></section>`}
function workspace(){return `<section class="panel"><p class="eyebrow">Workspace</p><h1>Inspect evidence without mutating it</h1><label>Capsule directory or .rcap path</label><input id="path" value="${esc(state.path)}" placeholder="/path/to/capsule"><div class="actions"><button data-api="/api/v1/workspace/inspect">Inspect</button><button data-api="/api/v1/workspace/redaction-preview">Redaction preview</button><button data-api="/api/v1/workspace/timeline">Timeline</button></div>${feedback()}</section>`}
function integrity(){return `<section class="panel"><p class="eyebrow">Integrity</p><h1>Verify deterministic capsule integrity</h1><label>.rcap path</label><input id="path" value="${esc(state.path)}" placeholder="/path/to/finding.rcap"><div class="actions"><button data-api="/api/v1/verify">Verify</button></div>${feedback()}</section>`}
function capabilities(){return `<section class="panel"><p class="eyebrow">Runtime capabilities</p><h1>What this build actually implements</h1><div class="actions"><button data-simple="/api/v1/capabilities">Load capabilities</button></div>${feedback()}</section>`}
function render(){const body=state.view==='workspace'?workspace():state.view==='integrity'?integrity():state.view==='capabilities'?capabilities():dashboard();root.innerHTML=shell(body);root.querySelectorAll('[data-view]').forEach(x=>x.onclick=()=>{state.view=x.dataset.view;state.result=null;state.error='';render()});const input=root.querySelector('#path');if(input)input.oninput=e=>state.path=e.target.value;root.querySelectorAll('[data-api]').forEach(x=>x.onclick=()=>request(x.dataset.api,true));root.querySelectorAll('[data-simple]').forEach(x=>x.onclick=()=>request(x.dataset.simple,false))}
async function request(endpoint,withPath){state.error='';state.result=null;if(withPath&&!state.path.trim()){state.error='A local path is required.';render();return}try{const url=withPath?`${endpoint}?path=${encodeURIComponent(state.path)}`:endpoint;const r=await fetch(url);const b=await r.json();if(!r.ok)throw new Error(b.detail||b.error||'Request failed');state.result=b}catch(e){state.error=e instanceof Error?e.message:'Request failed'}render()}
render();fetch('/api/v1/health').then(r=>r.json()).then(x=>{state.health=x;render()}).catch(()=>{});
